name: Cypress E2E Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install root dependencies
        run: npm ci
      - name: Start server in the background
        run: npm start &

      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          working-directory: cypress
          browser: chrome
          wait-on: 'http://localhost:3000'
          config: baseUrl=http://localhost:3000
          wait-on-timeout: 120
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-artifacts
          path: cypress/screenshots/*, cypress/videos/*
          if-no-files-found: ignore
